import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
const port = 3260;
const server = spawn('node', ['scripts/serve.mjs', '--dir', 'dist', '--port', String(port)], { stdio: 'ignore' });
process.on('exit', () => server.kill());
await new Promise((r) => setTimeout(r, 700));
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 640, height: 360 } });
await page.goto(`http://localhost:${port}/?screen=race&track=neon&auto=1&q=low`, { timeout: 120000 });
await page.waitForFunction(() => window.__spg && window.__spg.ready, null, { timeout: 180000 });
await page.waitForTimeout(4000);
const snap = await page.evaluate(() => { const s = window.__spg.snapshot(); return { fps: s.fps, calls: s.drawCalls, tris: s.triangles, geos: s.geometries, tex: s.textures, extra2: s.extra2 }; });
console.log(JSON.stringify(snap, null, 1));
await browser.close();
process.exit(0);
